on:
  push:
    branches:
      - develop/*

permissions:
  contents: write
  pull-requests: write

name: create-pre-release

jobs:
  create-pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          prerelease: true
          default-branch: develop/sprint-1