name: Deploy API app

on:
  create:
    tags:
      - v*

jobs:
  deploy_to_dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    # environment: dev
    # env:
    #   AWS_REGION: us-east-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          TAG_NAME="${{ github.ref }}#refs/tags/"
          echo "The release tag is ${TAG_NAME#refs/tags/}"